version: '3'
services:
  cpp:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      - "8080:8080"
    volumes:
      - ../CppND-Memory-Management-Chatbot:/CppND-Memory-Management-Chatbot
      - ../mmgmt_chatbot/src:/CppND-Memory-Management-Chatbot/src
      - ../scripts/debug-project.sh:/debug-project.sh
    environment:
        - DISPLAY=docker.for.mac.host.internal:0
    command: >
      bash -c "
      chmod +x /debug-project.sh &&
      export DISPLAY=host.docker.internal:0 &&
      /debug-project.sh
      "
